CREATE TABLE ENDERECO_CLIENTE (
cep VARCHAR (8),
numero_CASA INTEGER,
id INTEGER PRIMARY KEY AUTOINCREMENT);

CREATE TABLE CLIENTE (id INTEGER PRIMARY KEY AUTOINCREMENT,
nm_completo TEXT,
nm_usuario TEXT,
email TEXT,
cpf VARCHAR (11),
dt_nascimento DATE,
id_endereco INTEGER,
FOREIGN KEY (id_endereco) REFERENCES ENDERECO_CLIENTE (id));

CREATE TABLE PEDIDO (
dt_pedido DATETIME,
id INTEGER PRIMARY KEY AUTOINCREMENT,
id_cliente INTEGER,
FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id));

CREATE TABLE CATEGORIA (
id INTEGER PRIMARY KEY AUTOINCREMENT,
descricao_cat TEXT,
nm_cat TEXT);

CREATE TABLE DESCRICAO_PRODUTO (
id INTEGER PRIMARY KEY AUTOINCREMENT,
dt_fabricacao DATE,
valor INTEGER,
peso INTEGER,
cor TEXT);

CREATE TABLE PRODUTO (
id INTEGER PRIMARY KEY AUTOINCREMENT,
nm_produto TEXT,
qnt_produto INTEGER,
id_categoria INTEGER,
id_descricao INTEGER,
FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id),
FOREIGN KEY (id_descricao) REFERENCES DESCRICAO_PRODUTO(id));

CREATE TABLE PRODUTO_ITEM(
id INTEGER PRIMARY KEY AUTOINCREMENT,
id_pedido INTEGER,
id_produto INTEGER,
FOREIGN KEY (id_pedido) REFERENCES PEDIDO(id),
FOREIGN KEY (id_produto) REFERENCES PRODUTO	(id));

CREATE TABLE FUNCIONARIO (
id INTEGER PRIMARY KEY AUTOINCREMENT,
cpf_funcionario VARCHAR (11),
nm_funcionario TEXT);

CREATE TABLE CADASTRO_PRODUTO(
id INTEGER PRIMARY KEY AUTOINCREMENT,
id_produto INTEGER,
id_funcionario INTEGER,
FOREIGN KEY (id_produto) REFERENCES PRODUTO(id),
FOREIGN KEY (id_funcionario) REFERENCES FUNCIONARIO(id));

