DROP TABLE IF EXISTS Funcionario;
CREATE TABLE Funcionario(
ID_Funcionario INTEGER PRIMARY KEY AUTOINCREMENT,
Nome TEXT NOT NULL,
CPF INTEGER NOT NULL);

DROP TABLE IF EXISTS Categoria;
CREATE TABLE Categoria(
ID_Categoria INTEGER PRIMARY KEY AUTOINCREMENT,
Tipo TEXT NOT NULL,
Descricao TEXT NOT NULL);

DROP TABLE IF EXISTS Produto;
CREATE TABLE Produto(
ID_Produto INTEGER PRIMARY KEY AUTOINCREMENT,
ID_Categoria INTEGER NOT NULL,
Nome TEXT NOT NULL,
Descrição TEXT NOT NULL,
Valor_unitário INTEGER NOT NULL,
Data_fabricacao DATA NOT NULL,
FOREIGN KEY (ID_Categoria) REFERENCES Categoria(ID_Categoria));

DROP TABLE IF EXISTS Estoque;
CREATE TABLE Estoque(
ID_Estoque INTEGER PRIMARY KEY AUTOINCREMENT,
ID_Produto INTEGER NOT NULL,
Quantidade_estoque INTEGER NOT NULL,
FOREIGN KEY (ID_Produto) REFERENCES Produto(ID_Produto));

DROP TABLE IF EXISTS Func_Prod;
CREATE TABLE Func_Prod(
ID_Func_Prod INTEGER PRIMARY KEY AUTOINCREMENT,
ID_Funcionario INTEGER NOT NULL,
ID_Produto INTEGER NOT NULL,
FOREIGN KEY (ID_Produto) REFERENCES Produto(ID_Produto),
FOREIGN KEY (ID_Funcionario) REFERENCES Funcionario(ID_Funcionario));

DROP TABLE IF EXISTS Endereco;
CREATE TABLE Endereco(
ID_Endereco INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
Logradouro TEXT NOT NULL,
Bairro TEXT NOT NULL,
Cep INTEGER NOT NULL);

DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente(
ID_Cliente INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
Nome_Completo TEXT NOT NULL,
Nome_Usuario TEXT NOT NULL,
Email TEXT NOT NULL,
CPF TEXT NOT NULL,
Data_Nascimento DATA NOT NULL,
ID_Endereco INTEGER NOT NULL,
FOREIGN KEY (ID_Endereco) REFERENCES Endereco(ID_Endereco));

DROP TABLE IF EXISTS Pedido;
CREATE TABLE Pedido(
ID_Pedido INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
ID_Cliente INTEGER NOT NULL,
Data_Pedido DATA NOT NULL,
Valor_Total INTEGER,
FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente));

DROP TABLE IF EXISTS Pedido_Item;
CREATE TABLE Pedido_Item(
ID_Pedido_Item INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
Quantidade INTEGER NOT NULL,
ID_Pedido INTEGER NOT NULL,
ID_Produto INTEGER NOT NULL,
FOREIGN KEY (ID_Pedido) REFERENCES Pedido(ID_Pedido),
FOREIGN KEY (ID_Produto) REFERENCES Produto(ID_Produto))